/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Accounts",
    "«Available Accounts»": "Account disponibili",
    "«Cancel»": "Annulla",
    "«Check every %i minutes»": "Controlla ogni %i minuti",
    "«Check now»": "Verifica adesso",
    "«Check on showing Dashboard»": "Controlla nella Dashboard",
    "«Done»": "Fatto",
    "«en.lproj/»": "it.lproj/",
    "«From»": "Da",
    "«New Mail»": "Nuova Posta",
    "«New Update Version %f»": "Aggiornamento Versione %f",
    "«Password»": "Password",
    "«Please press ⌘R to restart MailWidget.»": "Premi ⌘R per far ripartire MailWidget",
    "«Remove»": "Rimuovi",
    "«Select Accounts»": "Scegli account",
    "«Skip»": "Ignora",
    "«Subject»": "Oggetto",
    "«Update»": "Aggiorna",
    "«Verify»": "Verifica",
    "«Volume: %i»": "Volume %i",
    "«What is new?»": "Nuove caratteristiche"
};

