/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Cuentas",
    "«Available Accounts»": "Cuentas Disponibles",
    "«Cancel»": "Cancelar",
    "«Check every %i minutes»": "Cada %i minutos",
    "«Check now»": "Buscar ahora",
    "«Check on showing Dashboard»": "Al mostrar Dashboard",
    "«Done»": "Salir",
    "«en.lproj/»": "es.lproj/",
    "«From»": "De",
    "«New Mail»": "Correo Nuevo",
    "«New Update Version %f»": "Actualización a la Versión %f",
    "«Password»": "Contraseña",
    "«Please press ⌘R to restart MailWidget.»": "Por favor, presione ⌘R para reiniciar MailWidget",
    "«Remove»": "Eliminar",
    "«Select Accounts»": "Seleccionar Cuentas",
    "«Skip»": "Omitir",
    "«Subject»": "Asunto",
    "«Update»": "Actualizar",
    "«Verify»": "Verificar",
    "«Volume: %i»": "Volúmen %i",
    "«What is new?»": "¿Qué es nuevo?"
};

