/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Konten",
    "«Available Accounts»": "Verfügbare Konten",
    "«Cancel»": "Abbrechen",
    "«Check every %i minutes»": "Prüfe alle %i Minuten",
    "«Check now»": "Jetzt suchen",
    "«Check on showing Dashboard»": "Beim Öffnen von Dashboard",
    "«Done»": "Fertig",
    "«en.lproj/»": "de.lproj/",
    "«From»": "Absender",
    "«New Mail»": "Neue Post",
    "«New Update Version %f»": "Neues Update Version %f",
    "«Password»": "Kennwort",
    "«Please press ⌘R to restart MailWidget.»": "Bitte drücken Sie ⌘R um die neue Version zu initialisieren.",
    "«Remove»": "Abbrechen",
    "«Select Accounts»": "Konten wählen",
    "«Skip»": "Später",
    "«Subject»": "Betreff",
    "«Update»": "Aktualisieren",
    "«Verify»": "Prüfen",
    "«Volume: %i»": "Lautstärke: %i",
    "«What is new?»": "Was ist neu?"
};

