/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Comptes",
    "«Available Accounts»": "Comptes disponibles",
    "«Cancel»": "Annuler",
    "«Check every %i minutes»": "Toutes les %i minutes",
    "«Check now»": "Rechercher",
    "«Check on showing Dashboard»": "Si Dashboard est visible",
    "«Done»": "Terminé",
    "«en.lproj/»": "fr.lproj/",
    "«From»": "De",
    "«New Mail»": "Nouveau courrier",
    "«New Update Version %f»": "Mise à jour version %f",
    "«Password»": "Mot de passe",
    "«Please press ⌘R to restart MailWidget.»": "S'il vous plaît appuyer sur ⌘R pour initialiser",
    "«Remove»": "Effacer",
    "«Select Accounts»": "Choisir les comptes",
    "«Skip»": "Sauter",
    "«Subject»": "Objet",
    "«Update»": "Installer",
    "«Verify»": "Vérifier",
    "«Volume: %i»": "Volume %i",
    "«What is new?»": "Nouveautés"
};

