/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Accounts",
    "«Available Accounts»": "Available Accounts",
    "«Cancel»": "Cancel",
    "«Check every %i minutes»": "Check every %i minutes",
    "«Check now»": "Check Now",
    "«Check on showing Dashboard»": "On showing Dashboard",
    "«Done»": "Done",
    "«en.lproj/»": "en.lproj/",
    "«From»": "From",
    "«New Mail»": "New Mail",
    "«New Update Version %f»": "New Update Version %f",
    "«Password»": "Password",
    "«Please press ⌘R to restart MailWidget.»": "Please press ⌘R to restart MailWidget.",
    "«Remove»": "Remove",
    "«Select Accounts»": "Select Accounts",
    "«Skip»": "Skip",
    "«Subject»": "Subject",
    "«Update»": "Update",
    "«Verify»": "Verify",
    "«Volume: %i»": "Volume: %i",
    "«What is new?»": "What is new?"
};

