/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "«Accounts»": "Användare",
    "«Available Accounts»": "Tillgängliga Användare",
    "«Cancel»": "Avbryt",
    "«Check every %i minutes»": "Kontrollera varje %i min",
    "«Check now»": "Uppdatera nu",
    "«Check on showing Dashboard»": "När Dashboard är synlig",
    "«Done»": "Klart",
    "«en.lproj/»": "sv.lproj/",
    "«From»": "Från",
    "«New Mail»": "Nytt e-postmeddelande",
    "«New Update Version %f»": "Uppdatera till Version %f",
    "«Password»": "Lösenord",
    "«Please press ⌘R to restart MailWidget.»": "Var god och klicka på ⌘R för att starta om MailWidget",
    "«Remove»": "Ta bort",
    "«Select Accounts»": "Välj Användare",
    "«Skip»": "Senare",
    "«Subject»": "Ämne",
    "«Update»": "Uppdatera",
    "«Verify»": "Verifiera",
    "«Volume: %i»": "Volym %i",
    "«What is new?»": "Vad är nytt?"
};

